-- ==============================================================================
-- DIPRE STUDIO / DISCORDRPG — SUPABASE POSTGRESQL SCHEMA INITIALIZATION
-- Hướng dẫn: Mở Supabase Dashboard -> Chọn Project -> SQL Editor -> Dán toàn bộ script này -> Run
-- ==============================================================================

-- 1. Bảng quản lý Bot Applications Discord của người dùng
CREATE TABLE IF NOT EXISTS public.discord_bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    app_id TEXT NOT NULL,
    bot_name TEXT NOT NULL,
    bot_avatar_url TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Bảng Diễn Đàn Templates RPC Cộng Đồng
CREATE TABLE IF NOT EXISTS public.rpc_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT,
    author_name TEXT DEFAULT 'DIPRE Member',
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    tags JSONB DEFAULT '[]'::jsonb,
    rpc_config JSONB NOT NULL,
    preview_image_url TEXT DEFAULT '',
    is_public BOOLEAN DEFAULT true,
    likes_count INTEGER DEFAULT 0,
    uses_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Bảng Lưu Trữ Mẫu Yêu Thích & Lượt Thích
CREATE TABLE IF NOT EXISTS public.template_favorites (
    user_id BIGINT NOT NULL,
    template_id BIGINT REFERENCES public.rpc_templates(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (user_id, template_id)
);

-- 4. Kích hoạt phân quyền đọc công khai cho Diễn đàn (Row Level Security)
ALTER TABLE public.rpc_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.discord_bots ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cho phép đọc template công khai" 
ON public.rpc_templates FOR SELECT 
USING (is_public = true);

CREATE POLICY "Cho phép tạo template mới" 
ON public.rpc_templates FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Cho phép cập nhật lượt dùng & like" 
ON public.rpc_templates FOR UPDATE 
USING (true);

CREATE POLICY "Cho phép truy cập bot applications" 
ON public.discord_bots FOR ALL 
USING (true);
